spring.application.name=food-delivery-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/food_delivery_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root@123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8081}

# JWT Configuration
jwt.secret=${JWT_SECRET:VGhpcy1pcy1hLXNlY3VyZS1kZXZlbG9wbWVudC1qd3Qtc2VjcmV0LWtleS0xMjM0NTY3ODkw}
jwt.expiration=86400000